# generated by datamodel-codegen:
#   filename:  1.json
#   timestamp: 2026-08-31T13:56:42+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class HabilitacaoItem(BaseModel):
    nomeHabilitacao: str
    dataHabilitacao: str


class Autorizacao(BaseModel):
    Tipo: str
    Numero: str
    Data: str
    DataPublicacao: str


class Reconhecimento(BaseModel):
    Tipo: str
    Numero: str
    Data: str
    VeiculoPublicacao: str
    DataPublicacao: str
    SecaoPublicacao: str
    PaginaPublicacao: str


class RenovacaoReconhecimento(BaseModel):
    Tipo: str
    Numero: str
    Data: str
    VeiculoPublicacao: str
    DataPublicacao: str
    SecaoPublicacao: str
    PaginaPublicacao: str
    NumeroDOU: str


class DadosCurso(BaseModel):
    nomeCurso: str
    habilitacao: list[HabilitacaoItem]
    autorizacao: Autorizacao
    reconhecimento: Reconhecimento
    renovacaoReconhecimento: RenovacaoReconhecimento
    codigoCursoEMEC: str


class Endereco(BaseModel):
    Logradouro: str
    Numero: str
    Bairro: str
    CodigoMunicipio: str
    NomeMunicipio: str
    UF: str
    CEP: str


class Credenciamento(BaseModel):
    Tipo: str
    Numero: str
    Data: str
    VeiculoPublicacao: str
    DataPublicacao: str
    SecaoPublicacao: str
    PaginaPublicacao: str


class Recredenciamento(BaseModel):
    Tipo: str
    Numero: str
    Data: str
    VeiculoPublicacao: str
    DataPublicacao: str
    SecaoPublicacao: str
    PaginaPublicacao: str


class RenovacaoDeRecredenciamento(BaseModel):
    Tipo: str
    Numero: str
    Data: str
    VeiculoPublicacao: str
    DataPublicacao: str
    SecaoPublicacao: str
    PaginaPublicacao: str
    NumeroDOU: str


class Mantenedora(BaseModel):
    RazaoSocial: str
    CNPJ: str
    Endereco_1: Endereco = Field(..., alias='Endereco')


class IesEmissora(BaseModel):
    Nome: str
    CodigoMEC: str
    endereco: Endereco
    Cnpj: str
    credenciamento: Credenciamento
    recredenciamento: Recredenciamento
    renovacaoDeRecredenciamento: RenovacaoDeRecredenciamento
    mantenedora: Mantenedora


class EtiquetaItem(BaseModel):
    codigo: str
    nome: str


class UnidadeCurricularItem(BaseModel):
    tipo: str
    codigo: str
    nome: str
    cargaHorariaEmHoraAula: str
    cargaHorariaEmHoraRelogio: str


class Atividade(BaseModel):
    codigo: str
    nome: str
    limiteCargaHorariaEmHoraRelogio: str


class CategoriaItem(BaseModel):
    codigo: str
    nome: str
    atividades: list[Atividade]


class CargasHorariasCriterio(BaseModel):
    cargaHorariaMinima: str
    cargaHorariaMaxima: str


class CriterioIntegralizacaoRotulo(BaseModel):
    codigo: str
    unidadeCurricular: str
    cargasHorariasCriterio: CargasHorariasCriterio


class Model(BaseModel):
    codigoCurriculo: str
    dataCurriculo: str
    minutosRelogioDaHoraAula: str
    dadosCurso: DadosCurso
    iesEmissora: IesEmissora
    area: list[Any]
    etiqueta: list[EtiquetaItem]
    unidadeCurricular: list[UnidadeCurricularItem]
    categoria: list[CategoriaItem]
    criterioIntegralizacaoRotulos: list[CriterioIntegralizacaoRotulo]
