# generated by datamodel-codegen:
#   filename:  301.1973.json
#   timestamp: 2026-08-31T13:32:50+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Naturalidade(BaseModel):
    codigoMunicipio: str
    nomeMunicipio: str
    uf: str


class Rg(BaseModel):
    numero: str
    orgaoExpedidor: str
    uf: str


class Diplomado(BaseModel):
    id: str
    nome: str
    nomeSocial: str
    sexo: str
    nacionalidade: str
    naturalidade: Naturalidade
    cpf: str
    dataNascimento: str
    rg: Rg


class HabilitacaoItem(BaseModel):
    nomeHabilitacao: str
    dataHabilitacao: str


class TituloConferido(BaseModel):
    Titulo: str


class EnderecoCurso(BaseModel):
    logradouro: str
    numero: str
    bairro: str
    codigoMunicipio: str
    nomeMunicipio: str
    uf: str
    cep: str


class Endereco(BaseModel):
    Logradouro: str
    Numero: str
    Bairro: str
    CodigoMunicipio: str
    NomeMunicipio: str
    UF: str
    CEP: str


class Polo(BaseModel):
    Nome: str
    Endereco_1: Endereco = Field(..., alias='Endereco')
    CodigoEMEC: str


class Autorizacao(BaseModel):
    Tipo: str
    Numero: str
    Data: str
    DataPublicacao: str


class Reconhecimento(BaseModel):
    Tipo: str
    Numero: str
    Data: str
    VeiculoPublicacao: str
    DataPublicacao: str
    SecaoPublicacao: str
    PaginaPublicacao: str


class RenovacaoReconhecimento(BaseModel):
    Tipo: str
    Numero: str
    Data: str
    VeiculoPublicacao: str
    DataPublicacao: str
    SecaoPublicacao: str
    PaginaPublicacao: str
    NumeroDOU: str


class DadosCurso(BaseModel):
    nomeCurso: str
    habilitacao: list[HabilitacaoItem]
    modalidade: str
    tituloConferido: TituloConferido
    grauConferido: str
    enderecoCurso: EnderecoCurso
    polo: Polo
    autorizacao: Autorizacao
    reconhecimento: Reconhecimento
    renovacaoReconhecimento: RenovacaoReconhecimento
    codigoCursoEMEC: str


class Credenciamento(BaseModel):
    Tipo: str
    Numero: str
    Data: str
    VeiculoPublicacao: str
    DataPublicacao: str
    SecaoPublicacao: str
    PaginaPublicacao: str


class Recredenciamento(BaseModel):
    Tipo: str
    Numero: str
    Data: str
    VeiculoPublicacao: str
    DataPublicacao: str
    SecaoPublicacao: str
    PaginaPublicacao: str


class RenovacaoDeRecredenciamento(BaseModel):
    Tipo: str
    Numero: str
    Data: str
    VeiculoPublicacao: str
    DataPublicacao: str
    SecaoPublicacao: str
    PaginaPublicacao: str
    NumeroDOU: str


class Mantenedora(BaseModel):
    RazaoSocial: str
    CNPJ: str
    Endereco_1: Endereco = Field(..., alias='Endereco')


class IesEmissora(BaseModel):
    nome: str
    codigoMEC: str
    cnpj: str
    endereco: Endereco
    credenciamento: Credenciamento
    recredenciamento: Recredenciamento
    renovacaoDeRecredenciamento: RenovacaoDeRecredenciamento
    mantenedora: Mantenedora


class DadosDiploma(BaseModel):
    diplomado: Diplomado
    dataConclusao: str
    dadosCurso: DadosCurso
    iesEmissora: IesEmissora


class Mantenedora1(BaseModel):
    RazaoSocial: str
    CNPJ: str
    Endereco_1: Endereco = Field(..., alias='Endereco')


class IesRegistradora(BaseModel):
    nome: str
    codigoMEC: str
    cnpj: str
    endereco: Endereco
    credenciamento: Credenciamento
    recredenciamento: Recredenciamento
    renovacaoDeRecredenciamento: RenovacaoDeRecredenciamento
    mantenedora: Mantenedora1


class ResponsavelRegistro(BaseModel):
    nome: str
    cpf: str
    iDouNumeroMatricula: str


class LivroRegistro(BaseModel):
    LivroRegistro: str
    ProcessoDoDiploma: str
    DataColacaoGrau: str
    DataExpedicaoDiploma: str
    DataRegistroDiploma: str
    ResponsavelRegistro_1: ResponsavelRegistro = Field(..., alias='ResponsavelRegistro')
    NumeroFolhaDoDiploma: str
    NumeroSequenciaDoDiploma: str


class DadosRegistro(BaseModel):
    iesRegistradora: IesRegistradora
    livroRegistro: LivroRegistro


class FiliacaoItem(BaseModel):
    nome: str
    nomeSocial: str
    sexo: str


class CargaHorariaEmHoraRelogioItem(BaseModel):
    value: str


class DocentesResponsaveisPelaValidacaoItem(BaseModel):
    nome: str
    titulacao: str
    cpf: str


class AtividadeComplementarItem(BaseModel):
    codigoAtividadeComplementar: str
    dataInicio: str
    dataFim: str
    tipoAtividadeComplementar: str
    cargaHorariaEmHoraRelogio: list[CargaHorariaEmHoraRelogioItem]
    docentesResponsaveisPelaValidacao: list[DocentesResponsaveisPelaValidacaoItem]


class CargaHorariaItem(BaseModel):
    horaAula: str
    horaRelogio: str


class Docente(BaseModel):
    nome: str
    titulacao: str
    cpf: str


class Aprovado(BaseModel):
    formaIntegralizacao: str


class DisciplinaItem(BaseModel):
    codigoDisciplina: str
    nomeDisciplina: str
    periodoLetivo: str
    cargaHoraria: list[CargaHorariaItem]
    docentes: list[Docente]
    nota: str | None = None
    notaAteCem: str | None = None
    aprovado: Aprovado
    conceitoEspecificoDoCurso: str | None = None


class CargaHorariaEmHorasRelogioItem(BaseModel):
    value: str


class DocentesOrientadore(BaseModel):
    nome: str
    titulacao: str
    cpf: str


class EstagioItem(BaseModel):
    codigoUnidadeCurricular: str
    dataInicio: str
    dataFim: str
    cargaHorariaEmHorasRelogio: list[CargaHorariaEmHorasRelogioItem]
    docentesOrientadores: list[DocentesOrientadore]


class Formado(BaseModel):
    dataConclusaoCurso: str
    dataColacaoGrau: str
    dataExpedicaoDiploma: str


class SituacaoDiscenteItem(BaseModel):
    periodoLetivo: str
    formado: Formado


class ElementosHistorico(BaseModel):
    atividadeComplementar: list[AtividadeComplementarItem]
    disciplina: list[DisciplinaItem]
    estagio: list[EstagioItem]
    situacaoDiscente: list[SituacaoDiscenteItem]


class SituacaoAtualDiscente(BaseModel):
    periodoLetivo: str
    formado: Formado


class NaoHabilitadoItem(BaseModel):
    condicao: str
    edicao: str
    motivo: str


class Enade(BaseModel):
    naoHabilitado: list[NaoHabilitadoItem]


class CargaHorariaCursoIntegralizada(BaseModel):
    HoraAula: str
    HoraRelogio: str


class CargaHorariaCurso(BaseModel):
    horaAula: str
    horaRelogio: str


class IngressoCurso(BaseModel):
    data: str
    formaAcesso: str


class HistoricoEscolar(BaseModel):
    codigoCurriculo: str
    elementosHistorico: ElementosHistorico
    dataEmissaoHistorico: str
    horaEmissaoHistorico: str
    situacaoAtualDiscente: SituacaoAtualDiscente
    enade: Enade
    cargaHorariaCursoIntegralizada: CargaHorariaCursoIntegralizada
    cargaHorariaCurso: CargaHorariaCurso
    ingressoCurso: IngressoCurso


class DadosPrivadosDiplomado(BaseModel):
    filiacao: list[FiliacaoItem]
    historicoEscolar: HistoricoEscolar


class TermoResponsabilidade(BaseModel):
    Nome: str
    CPF: str
    Cargo: str


class Model(BaseModel):
    id: str
    dadosDiploma: DadosDiploma
    dadosRegistro: DadosRegistro
    dadosPrivadosDiplomado: DadosPrivadosDiplomado
    termoResponsabilidade: TermoResponsabilidade
