# generated by datamodel-codegen:
#   filename:  023.15729.json
#   timestamp: 2026-08-31T13:24:21+00:00

from __future__ import annotations

from pydantic import BaseModel


class Naturalidade(BaseModel):
    codigoMunicipio: str
    nomeMunicipio: str
    uf: str


class Rg(BaseModel):
    numero: str
    uf: str
    orgaoExpedidor: str


class Aluno(BaseModel):
    id: str
    nome: str
    nomeSocial: str
    sexo: str
    nacionalidade: str
    naturalidade: Naturalidade
    cpf: str
    dataNascimento: str
    rg: Rg


class Autorizacao(BaseModel):
    tipo: str
    numero: str
    data: str
    veiculoPublicacao: str
    dataPublicacao: str


class Reconhecimento(BaseModel):
    tipo: str
    numero: str
    data: str
    veiculoPublicacao: str
    dataPublicacao: str
    secaoPublicacao: str
    paginaPublicacao: str


class RenovacaoReconhecimento(BaseModel):
    tipo: str
    numero: str
    data: str
    veiculoPublicacao: str
    dataPublicacao: str
    secaoPublicacao: str
    paginaPublicacao: str


class HabilitacaoItem(BaseModel):
    nomeHabilitacao: str
    dataHabilitacao: str


class DadosCurso(BaseModel):
    nomeCurso: str
    codigoCursoEMEC: str
    autorizacao: Autorizacao
    reconhecimento: Reconhecimento
    renovacaoReconhecimento: RenovacaoReconhecimento
    habilitacao: list[HabilitacaoItem]


class Endereco(BaseModel):
    logradouro: str
    numero: str
    bairro: str
    codigoMunicipio: str
    nomeMunicipio: str
    uf: str
    cep: str


class Credenciamento(BaseModel):
    tipo: str
    numero: str
    data: str
    veiculoPublicacao: str
    dataPublicacao: str
    secaoPublicacao: str
    paginaPublicacao: str


class Recredenciamento(BaseModel):
    tipo: str
    numero: str
    data: str
    veiculoPublicacao: str
    dataPublicacao: str
    secaoPublicacao: str
    paginaPublicacao: str


class RenovacaoDeRecredenciamento(BaseModel):
    tipo: str
    numero: str
    data: str
    veiculoPublicacao: str
    dataPublicacao: str
    secaoPublicacao: str
    paginaPublicacao: str


class Mantenedora(BaseModel):
    razaoSocial: str
    cNPJ: str
    endereco: Endereco


class IesEmissora(BaseModel):
    nome: str
    codigoMEC: str
    cNPJ: str
    endereco: Endereco
    credenciamento: Credenciamento
    recredenciamento: Recredenciamento
    renovacaoDeRecredenciamento: RenovacaoDeRecredenciamento
    mantenedora: Mantenedora


class CargaHorariaEmHoraRelogioItem(BaseModel):
    value: str


class DocentesResponsaveisPelaValidacaoItem(BaseModel):
    nome: str
    titulacao: str
    cPF: str


class AtividadeComplementarItem(BaseModel):
    codigoAtividadeComplementar: str
    dataRegistro: str
    dataFim: str
    dataInicio: str
    tipoAtividadeComplementar: str
    descricao: str
    cargaHorariaEmHoraRelogio: list[CargaHorariaEmHoraRelogioItem]
    docentesResponsaveisPelaValidacao: list[DocentesResponsaveisPelaValidacaoItem]


class CargaHorariaItem(BaseModel):
    horaRelogio: str
    horaAula: str


class Docente(BaseModel):
    nome: str
    titulacao: str
    cPF: str
    lattes: str | None = None


class Aprovado(BaseModel):
    formaIntegralizacao: str


class DisciplinaItem(BaseModel):
    periodoLetivo: str
    cargaHoraria: list[CargaHorariaItem]
    codigoDisciplina: str
    docentes: list[Docente]
    nota: str | None = None
    aprovado: Aprovado
    nomeDisciplina: str
    notaAteCem: str | None = None
    conceitoEspecificoDoCurso: str | None = None


class DocentesOrientadore(BaseModel):
    nome: str
    titulacao: str
    cPF: str


class CargaHorariaEmHorasRelogioItem(BaseModel):
    value: str


class EstagioItem(BaseModel):
    codigoUnidadeCurricular: str
    descricao: str
    docentesOrientadores: list[DocentesOrientadore]
    dataFim: str
    dataInicio: str
    cargaHorariaEmHorasRelogio: list[CargaHorariaEmHorasRelogioItem]


class Formado(BaseModel):
    dataExpedicaoDiploma: str
    dataConclusaoCurso: str
    dataColacaoGrau: str


class SituacaoDiscenteItem(BaseModel):
    periodoLetivo: str
    formado: Formado


class ElementosHistorico(BaseModel):
    atividadeComplementar: list[AtividadeComplementarItem]
    disciplina: list[DisciplinaItem]
    estagio: list[EstagioItem]
    situacaoDiscente: list[SituacaoDiscenteItem]


class SituacaoAtualDiscente(BaseModel):
    formado: Formado


class NaoHabilitadoItem(BaseModel):
    condicao: str
    motivo: str
    edicao: str


class Enade(BaseModel):
    naoHabilitado: list[NaoHabilitadoItem]


class CargaHorariaCursoIntegralizada(BaseModel):
    horaAula: str
    horaRelogio: str


class CargaHorariaCurso(BaseModel):
    horaAula: str
    horaRelogio: str


class IngressoCurso(BaseModel):
    formaAcesso: str
    data: str


class HistoricoEscolar(BaseModel):
    codigoCurriculo: str
    elementosHistorico: ElementosHistorico
    dataEmissaoHistorico: str
    horaEmissaoHistorico: str
    situacaoAtualDiscente: SituacaoAtualDiscente
    enade: Enade
    cargaHorariaCursoIntegralizada: CargaHorariaCursoIntegralizada
    cargaHorariaCurso: CargaHorariaCurso
    ingressoCurso: IngressoCurso


class DocumentoHistoricoEscolarFinal(BaseModel):
    aluno: Aluno
    dadosCurso: DadosCurso
    iesEmissora: IesEmissora
    historicoEscolar: HistoricoEscolar
    informacoesAdicionais: str


class Model(BaseModel):
    id: str
    documentoHistoricoEscolarFinal: DocumentoHistoricoEscolarFinal
