"""Add document execution engine fields

Revision ID: 0cf467d9c35c
Revises: 80b509b6ce6d
Create Date: 2026-08-31 16:25:55.670494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0cf467d9c35c'
down_revision: Union[str, Sequence[str], None] = '80b509b6ce6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ged_document_index_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('index_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['ged_documents.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['ged_indices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_document_index_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_document_index_values_document_id'), ['document_id'], unique=False)

    with op.batch_alter_table('ged_document_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'ged_workflows', ['workflow_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ged_document_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workflow_id')

    with op.batch_alter_table('ged_document_index_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_document_index_values_document_id'))

    op.drop_table('ged_document_index_values')
    # ### end Alembic commands ###
