"""initial schema

Revision ID: 0d90561ea956
Revises: 
Create Date: 2026-08-29 16:26:16.135030
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0d90561ea956'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_institutions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_name'), ['name'], unique=False)

    op.create_table('schema_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('xsd_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schema_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schema_versions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_schema_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schema_versions_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_schema_versions_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_schema_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schema_versions_status'), ['status'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_institution_id'), ['institution_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_course_name'), ['course_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_year'), ['year'], unique=False)

    op.create_table('guardians',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardians_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_guardians_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardians_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardians_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardians_student_id'), ['student_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('enrollment_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_student_id'), ['student_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_id'), ['id'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_versions_uploaded_at'), ['uploaded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_document_versions_id'))
        batch_op.drop_index(batch_op.f('ix_document_versions_document_id'))

    op.drop_table('document_versions')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity'))
        batch_op.drop_index(batch_op.f('ix_audit_events_document_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_student_id'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_institution_id'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))

    op.drop_table('documents')
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardians_student_id'))
        batch_op.drop_index(batch_op.f('ix_guardians_id'))
        batch_op.drop_index(batch_op.f('ix_guardians_full_name'))
        batch_op.drop_index(batch_op.f('ix_guardians_email'))
        batch_op.drop_index(batch_op.f('ix_guardians_cpf'))

    op.drop_table('guardians')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_year'))
        batch_op.drop_index(batch_op.f('ix_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_status'))
        batch_op.drop_index(batch_op.f('ix_enrollments_institution_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_course_name'))

    op.drop_table('enrollments')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_institution_id'))
        batch_op.drop_index(batch_op.f('ix_students_id'))
        batch_op.drop_index(batch_op.f('ix_students_full_name'))
        batch_op.drop_index(batch_op.f('ix_students_email'))
        batch_op.drop_index(batch_op.f('ix_students_cpf'))

    op.drop_table('students')
    with op.batch_alter_table('schema_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schema_versions_status'))
        batch_op.drop_index(batch_op.f('ix_schema_versions_id'))
        batch_op.drop_index(batch_op.f('ix_schema_versions_environment'))
        batch_op.drop_index(batch_op.f('ix_schema_versions_document_type'))
        batch_op.drop_index(batch_op.f('ix_schema_versions_created_at'))
        batch_op.drop_index(batch_op.f('ix_schema_versions_code'))

    op.drop_table('schema_versions')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_name'))
        batch_op.drop_index(batch_op.f('ix_institutions_id'))
        batch_op.drop_index(batch_op.f('ix_institutions_cnpj'))

    op.drop_table('institutions')
    # ### end Alembic commands ###
