"""restrict_on_delete_constraints

Revision ID: 0f25e1d72b31
Revises: 5542cfaeccbf
Create Date: 2026-09-09 20:58:59.245647
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f25e1d72b31'
down_revision: Union[str, Sequence[str], None] = '5542cfaeccbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_events_user_id_fkey'), 'audit_events', type_='foreignkey')
    op.create_foreign_key(None, 'audit_events', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('ecm_dynamic_aspects_institution_id_fkey'), 'ecm_dynamic_aspects', type_='foreignkey')
    op.create_foreign_key(None, 'ecm_dynamic_aspects', 'institutions', ['institution_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('ecm_nodes_institution_id_fkey'), 'ecm_nodes', type_='foreignkey')
    op.drop_constraint(op.f('ecm_nodes_created_by_fkey'), 'ecm_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'ecm_nodes', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'ecm_nodes', 'institutions', ['institution_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('ecm_sites_created_by_fkey'), 'ecm_sites', type_='foreignkey')
    op.drop_constraint(op.f('ecm_sites_institution_id_fkey'), 'ecm_sites', type_='foreignkey')
    op.create_foreign_key(None, 'ecm_sites', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'ecm_sites', 'institutions', ['institution_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('ged_document_type_versions_created_by_fkey'), 'ged_document_type_versions', type_='foreignkey')
    op.create_foreign_key(None, 'ged_document_type_versions', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('ged_workflow_tasks_assignee_id_fkey'), 'ged_workflow_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'ged_workflow_tasks', 'users', ['assignee_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ged_workflow_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('ged_workflow_tasks_assignee_id_fkey'), 'ged_workflow_tasks', 'users', ['assignee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'ged_document_type_versions', type_='foreignkey')
    op.create_foreign_key(op.f('ged_document_type_versions_created_by_fkey'), 'ged_document_type_versions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'ecm_sites', type_='foreignkey')
    op.drop_constraint(None, 'ecm_sites', type_='foreignkey')
    op.create_foreign_key(op.f('ecm_sites_institution_id_fkey'), 'ecm_sites', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('ecm_sites_created_by_fkey'), 'ecm_sites', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'ecm_nodes', type_='foreignkey')
    op.drop_constraint(None, 'ecm_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('ecm_nodes_created_by_fkey'), 'ecm_nodes', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('ecm_nodes_institution_id_fkey'), 'ecm_nodes', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'ecm_dynamic_aspects', type_='foreignkey')
    op.create_foreign_key(op.f('ecm_dynamic_aspects_institution_id_fkey'), 'ecm_dynamic_aspects', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.create_foreign_key(op.f('audit_events_user_id_fkey'), 'audit_events', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
