"""Add DashboardConfig

Revision ID: 2fb567aa54f3
Revises: d86c1ee600c7
Create Date: 2026-09-07 13:51:54.949997
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2fb567aa54f3'
down_revision: Union[str, Sequence[str], None] = 'd86c1ee600c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecm_dashboard_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('layout_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecm_dashboard_configs_owner_id'), 'ecm_dashboard_configs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ecm_dashboard_configs_owner_type'), 'ecm_dashboard_configs', ['owner_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecm_dashboard_configs_owner_type'), table_name='ecm_dashboard_configs')
    op.drop_index(op.f('ix_ecm_dashboard_configs_owner_id'), table_name='ecm_dashboard_configs')
    op.drop_table('ecm_dashboard_configs')
    # ### end Alembic commands ###
