"""Add document types and indices

Revision ID: 379a2272e39f
Revises: a962bef0764a
Create Date: 2026-08-31 15:49:58.549250
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '379a2272e39f'
down_revision: Union[str, Sequence[str], None] = 'a962bef0764a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ged_indices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_indices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_indices_name'), ['name'], unique=True)

    op.create_table('ged_document_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('storage_area_id', sa.String(), nullable=False),
    sa.Column('storage_partition_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['storage_area_id'], ['ged_storage_areas.id'], ),
    sa.ForeignKeyConstraint(['storage_partition_id'], ['ged_storage_partitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_document_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_document_types_name'), ['name'], unique=True)

    op.create_table('ged_document_type_indices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_type_id', sa.String(), nullable=False),
    sa.Column('index_id', sa.String(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_unique', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['ged_document_types.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['ged_indices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ged_document_type_indices')
    with op.batch_alter_table('ged_document_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_document_types_name'))

    op.drop_table('ged_document_types')
    with op.batch_alter_table('ged_indices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_indices_name'))

    op.drop_table('ged_indices')
    # ### end Alembic commands ###
