"""add user_id to audit_events

Revision ID: 49e3f227e659
Revises: f390c389aece
Create Date: 2026-09-05 15:14:10.889963
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49e3f227e659'
down_revision: Union[str, Sequence[str], None] = 'f390c389aece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_audit_events_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_events_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
