"""Add workflow models

Revision ID: 50e68a54c6f8
Revises: 379a2272e39f
Create Date: 2026-08-31 16:04:07.584742
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50e68a54c6f8'
down_revision: Union[str, Sequence[str], None] = '379a2272e39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ged_workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('internal_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_workflows_internal_name'), ['internal_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_ged_workflows_name'), ['name'], unique=True)

    op.create_table('ged_workflow_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_initial', sa.Boolean(), nullable=True),
    sa.Column('is_completion', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['ged_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ged_document_workflow_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('current_state_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_state_id'], ['ged_workflow_states.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['ged_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_document_workflow_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_document_workflow_instances_document_id'), ['document_id'], unique=False)

    op.create_table('ged_workflow_transitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('origin_state_id', sa.String(), nullable=False),
    sa.Column('destination_state_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['destination_state_id'], ['ged_workflow_states.id'], ),
    sa.ForeignKeyConstraint(['origin_state_id'], ['ged_workflow_states.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['ged_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ged_workflow_transitions')
    with op.batch_alter_table('ged_document_workflow_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_document_workflow_instances_document_id'))

    op.drop_table('ged_document_workflow_instances')
    op.drop_table('ged_workflow_states')
    with op.batch_alter_table('ged_workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_workflows_name'))
        batch_op.drop_index(batch_op.f('ix_ged_workflows_internal_name'))

    op.drop_table('ged_workflows')
    # ### end Alembic commands ###
