"""dynamic_aspects

Revision ID: 5542cfaeccbf
Revises: 8c4f1e2a7b90
Create Date: 2026-09-09 20:21:47.968041
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5542cfaeccbf'
down_revision: Union[str, Sequence[str], None] = '8c4f1e2a7b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecm_dynamic_aspects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('institution_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecm_dynamic_aspects_name'), 'ecm_dynamic_aspects', ['name'], unique=True)
    op.create_table('ecm_dynamic_properties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('aspect_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('multiple', sa.Boolean(), nullable=True),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['aspect_id'], ['ecm_dynamic_aspects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecm_dynamic_properties')
    op.drop_index(op.f('ix_ecm_dynamic_aspects_name'), table_name='ecm_dynamic_aspects')
    op.drop_table('ecm_dynamic_aspects')
    # ### end Alembic commands ###
