"""Add multi-cloud and duplication fields to storage partitions

Revision ID: 5e7a49782304
Revises: da819fe1df1d
Create Date: 2026-09-08 21:45:47.236699
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e7a49782304'
down_revision: Union[str, Sequence[str], None] = 'da819fe1df1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ged_storage_partitions', sa.Column('storage_type', sa.String(), nullable=True))
    op.add_column('ged_storage_partitions', sa.Column('enable_duplication', sa.Boolean(), nullable=True))
    op.add_column('ged_storage_partitions', sa.Column('secondary_storage_type', sa.String(), nullable=True))
    op.add_column('ged_storage_partitions', sa.Column('secondary_base_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ged_storage_partitions', 'secondary_base_path')
    op.drop_column('ged_storage_partitions', 'secondary_storage_type')
    op.drop_column('ged_storage_partitions', 'enable_duplication')
    op.drop_column('ged_storage_partitions', 'storage_type')
    # ### end Alembic commands ###
