"""Add campus and document type rbac

Revision ID: 61ffa5cea571
Revises: 064963f122ad
Create Date: 2026-09-05 06:15:24.585631
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61ffa5cea571'
down_revision: Union[str, Sequence[str], None] = '064963f122ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campuses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campuses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campuses_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campuses_name'), ['name'], unique=False)

    op.create_table('ged_user_document_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('document_type_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['ged_document_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_user_document_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_user_document_types_document_type_id'), ['document_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ged_user_document_types_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_campus_id'), ['campus_id'], unique=False)
        batch_op.create_foreign_key('fk_documents_campus_id_campuses', 'campuses', ['campus_id'], ['id'])

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_enrollments_campus_id'), ['campus_id'], unique=False)
        batch_op.create_foreign_key('fk_enrollments_campus_id_campuses', 'campuses', ['campus_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_campus_id'), ['campus_id'], unique=False)
        batch_op.create_foreign_key('fk_students_campus_id_campuses', 'campuses', ['campus_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_campus_id'), ['campus_id'], unique=False)
        batch_op.create_foreign_key('fk_users_campus_id_campuses', 'campuses', ['campus_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_campus_id_campuses', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_campus_id'))
        batch_op.drop_column('campus_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_campus_id_campuses', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_campus_id'))
        batch_op.drop_column('campus_id')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_enrollments_campus_id_campuses', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_enrollments_campus_id'))
        batch_op.drop_column('campus_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_campus_id_campuses', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_campus_id'))
        batch_op.drop_column('campus_id')

    with op.batch_alter_table('ged_user_document_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_user_document_types_user_id'))
        batch_op.drop_index(batch_op.f('ix_ged_user_document_types_document_type_id'))

    op.drop_table('ged_user_document_types')
    with op.batch_alter_table('campuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campuses_name'))
        batch_op.drop_index(batch_op.f('ix_campuses_institution_id'))
        batch_op.drop_index(batch_op.f('ix_campuses_id'))

    op.drop_table('campuses')
    # ### end Alembic commands ###
