"""Add missing models

Revision ID: 64432ae7387b
Revises: f2cea394023b
Create Date: 2026-09-08 22:41:00.432116
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '64432ae7387b'
down_revision: Union[str, Sequence[str], None] = 'f2cea394023b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ged_schema_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_type_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('xsd_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['ged_document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ged_schema_versions')
    # ### end Alembic commands ###
