"""Add modality to GEDDocument

Revision ID: 7087e88cf649
Revises: 9d4ace78f10e
Create Date: 2026-08-31 14:00:49.300713
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7087e88cf649'
down_revision: Union[str, Sequence[str], None] = '9d4ace78f10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ged_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modality', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ged_documents_modality'), ['modality'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ged_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_documents_modality'))
        batch_op.drop_column('modality')

    # ### end Alembic commands ###
