"""Add templates model

Revision ID: 80b509b6ce6d
Revises: 50e68a54c6f8
Create Date: 2026-08-31 16:08:59.939133
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80b509b6ce6d'
down_revision: Union[str, Sequence[str], None] = '50e68a54c6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ged_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_templates_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ged_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_templates_name'))

    op.drop_table('ged_templates')
    # ### end Alembic commands ###
