"""Add FilaProcessamento

Revision ID: 829eb281d722
Revises: e4ae45eb7a31
Create Date: 2026-08-31 13:14:10.825861
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '829eb281d722'
down_revision: Union[str, Sequence[str], None] = 'e4ae45eb7a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ged_document_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('index_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_document_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_document_categories_index_code'), ['index_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_ged_document_categories_name'), ['name'], unique=False)

    op.create_table('ged_signers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('certificate_path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_signers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_signers_cpf'), ['cpf'], unique=True)

    op.create_table('ged_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'PENDENTE_VALIDACAO', 'REJEITADO', 'VALIDO', 'ASSINADO', 'ARQUIVADO', name='geddocumentstatus'), nullable=False),
    sa.Column('academic_phase', sa.Enum('MATRICULA', 'CURSO', 'FORMATURA', 'DIPLOMACAO', name='gedacademicphase'), nullable=True),
    sa.Column('extracted_metadata', sa.Text(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['ged_document_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_documents_student_id'), ['student_id'], unique=False)

    op.create_table('ged_document_transitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('from_status', sa.Enum('RASCUNHO', 'PENDENTE_VALIDACAO', 'REJEITADO', 'VALIDO', 'ASSINADO', 'ARQUIVADO', name='geddocumentstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('RASCUNHO', 'PENDENTE_VALIDACAO', 'REJEITADO', 'VALIDO', 'ASSINADO', 'ARQUIVADO', name='geddocumentstatus'), nullable=False),
    sa.Column('changed_by_user_id', sa.String(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['ged_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ged_external_ingestion_audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('raw_payload_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['ged_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_external_ingestion_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_external_ingestion_audit_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ged_external_ingestion_audit_idempotency_key'), ['idempotency_key'], unique=True)

    op.create_table('ged_fila_processamento',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('documento_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['ged_documents.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ged_fila_processamento')
    with op.batch_alter_table('ged_external_ingestion_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_external_ingestion_audit_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_ged_external_ingestion_audit_correlation_id'))

    op.drop_table('ged_external_ingestion_audit')
    op.drop_table('ged_document_transitions')
    with op.batch_alter_table('ged_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_documents_student_id'))

    op.drop_table('ged_documents')
    with op.batch_alter_table('ged_signers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_signers_cpf'))

    op.drop_table('ged_signers')
    with op.batch_alter_table('ged_document_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_document_categories_name'))
        batch_op.drop_index(batch_op.f('ix_ged_document_categories_index_code'))

    op.drop_table('ged_document_categories')
    # ### end Alembic commands ###
