"""Add ECM tags and versioning

Revision ID: 83e32e56e62b
Revises: dacf4e670455
Create Date: 2026-09-07 09:34:02.461467
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '83e32e56e62b'
down_revision: Union[str, Sequence[str], None] = 'dacf4e670455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecm_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecm_tags_name'), 'ecm_tags', ['name'], unique=True)
    op.create_table('ecm_node_tags',
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['ecm_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['ecm_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', 'tag_id')
    )
    op.add_column('ecm_nodes', sa.Column('major_version', sa.Integer(), nullable=False))
    op.add_column('ecm_nodes', sa.Column('minor_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecm_nodes', 'minor_version')
    op.drop_column('ecm_nodes', 'major_version')
    op.drop_table('ecm_node_tags')
    op.drop_index(op.f('ix_ecm_tags_name'), table_name='ecm_tags')
    op.drop_table('ecm_tags')
    # ### end Alembic commands ###
