"""Add callback_url to ExternalIngestionAudit

Revision ID: 9d4ace78f10e
Revises: ba0d30cd5bc5
Create Date: 2026-08-31 13:39:02.549945
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d4ace78f10e'
down_revision: Union[str, Sequence[str], None] = 'ba0d30cd5bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ged_external_ingestion_audit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('callback_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ged_external_ingestion_audit', schema=None) as batch_op:
        batch_op.drop_column('callback_url')

    # ### end Alembic commands ###
