"""Add node_type to WorkflowState

Revision ID: a1f0218f1c70
Revises: f0337e5c02a1
Create Date: 2026-09-13 16:00:11.215597
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1f0218f1c70'
down_revision: Union[str, Sequence[str], None] = 'f0337e5c02a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ged_workflow_states', sa.Column('node_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ged_workflow_states', 'node_type')
    # ### end Alembic commands ###
