"""Add versioning to GEDDocument

Revision ID: a4588b9baf7e
Revises: 0cf467d9c35c
Create Date: 2026-08-31 16:40:16.275386
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a4588b9baf7e'
down_revision: Union[str, Sequence[str], None] = '0cf467d9c35c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
