"""Add storage partitions

Revision ID: a962bef0764a
Revises: 7087e88cf649
Create Date: 2026-08-31 15:12:00.707567
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a962bef0764a'
down_revision: Union[str, Sequence[str], None] = '7087e88cf649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ged_storage_areas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_storage_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_storage_areas_name'), ['name'], unique=True)

    op.create_table('ged_storage_partitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('area_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_files', sa.Integer(), nullable=False),
    sa.Column('max_size_gb', sa.Float(), nullable=False),
    sa.Column('base_path', sa.String(), nullable=False),
    sa.Column('network_domain', sa.String(), nullable=True),
    sa.Column('network_user', sa.String(), nullable=True),
    sa.Column('network_password', sa.String(), nullable=True),
    sa.Column('current_file_count', sa.Integer(), nullable=True),
    sa.Column('current_size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['ged_storage_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ged_storage_partitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ged_storage_partitions_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ged_storage_partitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_storage_partitions_is_active'))

    op.drop_table('ged_storage_partitions')
    with op.batch_alter_table('ged_storage_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ged_storage_areas_name'))

    op.drop_table('ged_storage_areas')
    # ### end Alembic commands ###
