"""add_ingestion_job

Revision ID: a98b734d0fae
Revises: e864cf04d79f
Create Date: 2026-09-05 18:01:57.685782
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a98b734d0fae'
down_revision: Union[str, Sequence[str], None] = 'e864cf04d79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('manifest_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_institution_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_created_at'))

    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###
