"""migrate to ecm

Revision ID: a9955d1f706d
Revises: eae49c1dc210
Create Date: 2026-09-06 20:02:17.751397
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a9955d1f706d'
down_revision: Union[str, Sequence[str], None] = 'eae49c1dc210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecm_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['ecm_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecm_nodes_institution_id'), 'ecm_nodes', ['institution_id'], unique=False)
    op.create_index(op.f('ix_ecm_nodes_name'), 'ecm_nodes', ['name'], unique=False)
    op.create_index(op.f('ix_ecm_nodes_node_type'), 'ecm_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_ecm_nodes_parent_id'), 'ecm_nodes', ['parent_id'], unique=False)
    op.create_table('ecm_node_aspects',
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('aspect_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['ecm_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', 'aspect_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecm_node_aspects')
    op.drop_index(op.f('ix_ecm_nodes_parent_id'), table_name='ecm_nodes')
    op.drop_index(op.f('ix_ecm_nodes_node_type'), table_name='ecm_nodes')
    op.drop_index(op.f('ix_ecm_nodes_name'), table_name='ecm_nodes')
    op.drop_index(op.f('ix_ecm_nodes_institution_id'), table_name='ecm_nodes')
    op.drop_table('ecm_nodes')
    # ### end Alembic commands ###
