"""Add is_active to User

Revision ID: aca80a6ab77e
Revises: b28d02c3e541
Create Date: 2026-09-12 21:36:10.216351
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aca80a6ab77e'
down_revision: Union[str, Sequence[str], None] = 'b28d02c3e541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
