"""Add institution_id to GEDDocument

Revision ID: ba0d30cd5bc5
Revises: 829eb281d722
Create Date: 2026-08-31 13:34:32.731545
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba0d30cd5bc5'
down_revision: Union[str, Sequence[str], None] = '829eb281d722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ged_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ged_documents_institution_id'), ['institution_id'], unique=False)
        batch_op.create_foreign_key('fk_ged_documents_institution_id', 'institutions', ['institution_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ged_documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ged_documents_institution_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ged_documents_institution_id'))
        batch_op.drop_column('institution_id')

    # ### end Alembic commands ###
