"""enforce unique document versions

Revision ID: c23731ae19c6
Revises: 0d90561ea956
Create Date: 2026-08-29 16:28:21.989958
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c23731ae19c6'
down_revision: Union[str, Sequence[str], None] = '0d90561ea956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_document_versions_document_version', ['document_id', 'version_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_document_versions_document_version', type_='unique')

    # ### end Alembic commands ###
