"""Add ECM Sites and Members

Revision ID: d86c1ee600c7
Revises: 83e32e56e62b
Create Date: 2026-09-07 13:05:06.091564
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd86c1ee600c7'
down_revision: Union[str, Sequence[str], None] = '83e32e56e62b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecm_sites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecm_sites_institution_id'), 'ecm_sites', ['institution_id'], unique=False)
    op.create_index(op.f('ix_ecm_sites_name'), 'ecm_sites', ['name'], unique=False)
    op.create_table('ecm_site_members',
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['ecm_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('site_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecm_site_members')
    op.drop_index(op.f('ix_ecm_sites_name'), table_name='ecm_sites')
    op.drop_index(op.f('ix_ecm_sites_institution_id'), table_name='ecm_sites')
    op.drop_table('ecm_sites')
    # ### end Alembic commands ###
