"""Add WorkflowTask

Revision ID: d984f20d19c1
Revises: 2fb567aa54f3
Create Date: 2026-09-07 13:55:57.556061
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd984f20d19c1'
down_revision: Union[str, Sequence[str], None] = '2fb567aa54f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ged_workflow_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('assignee_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_id'], ['ged_document_workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ged_workflow_tasks_assignee_id'), 'ged_workflow_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_ged_workflow_tasks_instance_id'), 'ged_workflow_tasks', ['instance_id'], unique=False)
    op.create_index(op.f('ix_ged_workflow_tasks_status'), 'ged_workflow_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ged_workflow_tasks_status'), table_name='ged_workflow_tasks')
    op.drop_index(op.f('ix_ged_workflow_tasks_instance_id'), table_name='ged_workflow_tasks')
    op.drop_index(op.f('ix_ged_workflow_tasks_assignee_id'), table_name='ged_workflow_tasks')
    op.drop_table('ged_workflow_tasks')
    # ### end Alembic commands ###
