"""add institution_settings

Revision ID: e864cf04d79f
Revises: 49e3f227e659
Create Date: 2026-09-05 15:23:31.262579
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e864cf04d79f'
down_revision: Union[str, Sequence[str], None] = '49e3f227e659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('max_upload_size_mb', sa.Integer(), nullable=True),
    sa.Column('allowed_mime_types', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institution_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institution_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_institution_settings_institution_id'), ['institution_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institution_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institution_settings_institution_id'))
        batch_op.drop_index(batch_op.f('ix_institution_settings_id'))

    op.drop_table('institution_settings')
    # ### end Alembic commands ###
