"""Add workflow visual position

Revision ID: e900eb94f2b3
Revises: aca80a6ab77e
Create Date: 2026-09-13 11:31:24.349675
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e900eb94f2b3'
down_revision: Union[str, Sequence[str], None] = 'aca80a6ab77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ged_workflow_states', sa.Column('ui_pos_x', sa.Integer(), nullable=True))
    op.add_column('ged_workflow_states', sa.Column('ui_pos_y', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ged_workflow_states', 'ui_pos_y')
    op.drop_column('ged_workflow_states', 'ui_pos_x')
    # ### end Alembic commands ###
