"""Add SignatureLog

Revision ID: f0337e5c02a1
Revises: e900eb94f2b3
Create Date: 2026-09-13 14:05:55.778023
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f0337e5c02a1'
down_revision: Union[str, Sequence[str], None] = 'e900eb94f2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ged_signature_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('signature_type', sa.String(), nullable=False),
    sa.Column('original_file_hash', sa.String(), nullable=False),
    sa.Column('certificate_subject', sa.String(), nullable=True),
    sa.Column('certificate_issuer', sa.String(), nullable=True),
    sa.Column('tsa_timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['ged_documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ged_signature_logs_document_id'), 'ged_signature_logs', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ged_signature_logs_document_id'), table_name='ged_signature_logs')
    op.drop_table('ged_signature_logs')
    # ### end Alembic commands ###
