"""Refactor storage to unified rules

Revision ID: f2cea394023b
Revises: 5e7a49782304
Create Date: 2026-09-08 21:55:51.886170
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f2cea394023b'
down_revision: Union[str, Sequence[str], None] = '5e7a49782304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ged_storage_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('document_type_id', sa.String(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.Column('base_path', sa.String(), nullable=False),
    sa.Column('max_files_per_folder', sa.Integer(), nullable=True),
    sa.Column('max_gb_per_folder', sa.Float(), nullable=True),
    sa.Column('enable_duplication', sa.Boolean(), nullable=True),
    sa.Column('secondary_storage_type', sa.String(), nullable=True),
    sa.Column('secondary_base_path', sa.String(), nullable=True),
    sa.Column('network_domain', sa.String(), nullable=True),
    sa.Column('network_user', sa.String(), nullable=True),
    sa.Column('network_password', sa.String(), nullable=True),
    sa.Column('current_file_count', sa.Integer(), nullable=True),
    sa.Column('current_size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ged_storage_rules_is_active'), 'ged_storage_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_ged_storage_rules_name'), 'ged_storage_rules', ['name'], unique=False)
    op.drop_constraint(op.f('ged_document_types_storage_partition_id_fkey'), 'ged_document_types', type_='foreignkey')
    op.drop_constraint(op.f('ged_document_types_storage_area_id_fkey'), 'ged_document_types', type_='foreignkey')
    op.drop_column('ged_document_types', 'storage_area_id')
    op.drop_column('ged_document_types', 'storage_partition_id')
    op.drop_index(op.f('ix_ged_storage_partitions_is_active'), table_name='ged_storage_partitions')
    op.drop_table('ged_storage_partitions')
    op.drop_index(op.f('ix_ged_storage_areas_name'), table_name='ged_storage_areas')
    op.drop_table('ged_storage_areas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.create_table('ged_storage_areas',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ged_storage_areas_pkey'))
    )
    op.create_index(op.f('ix_ged_storage_areas_name'), 'ged_storage_areas', ['name'], unique=True)

    op.create_table('ged_storage_partitions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('area_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('max_files', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_size_gb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('base_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('network_domain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('network_user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('network_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_file_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('storage_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('enable_duplication', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('secondary_storage_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('secondary_base_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['ged_storage_areas.id'], name=op.f('ged_storage_partitions_area_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ged_storage_partitions_pkey'))
    )
    op.create_index(op.f('ix_ged_storage_partitions_is_active'), 'ged_storage_partitions', ['is_active'], unique=False)
    op.add_column('ged_document_types', sa.Column('storage_partition_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ged_document_types', sa.Column('storage_area_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('ged_document_types_storage_area_id_fkey'), 'ged_document_types', 'ged_storage_areas', ['storage_area_id'], ['id'])
    op.create_foreign_key(op.f('ged_document_types_storage_partition_id_fkey'), 'ged_document_types', 'ged_storage_partitions', ['storage_partition_id'], ['id'])
    op.drop_index(op.f('ix_ged_storage_rules_name'), table_name='ged_storage_rules')
    op.drop_index(op.f('ix_ged_storage_rules_is_active'), table_name='ged_storage_rules')
    op.drop_table('ged_storage_rules')
