"""add uploaded_by_user_id to ged_documents

Revision ID: f390c389aece
Revises: 61ffa5cea571
Create Date: 2026-09-05 15:05:38.691355
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f390c389aece'
down_revision: Union[str, Sequence[str], None] = '61ffa5cea571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ged_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by_user_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ged_documents_uploaded_by_user_id'), ['uploaded_by_user_id'], unique=False)
        batch_op.create_foreign_key('fk_ged_documents_uploaded_by_user_id_users', 'users', ['uploaded_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ged_documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ged_documents_uploaded_by_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ged_documents_uploaded_by_user_id'))
        batch_op.drop_column('uploaded_by_user_id')

    # ### end Alembic commands ###
