"""Update schema

Revision ID: fd7ce70edd59
Revises: d984f20d19c1
Create Date: 2026-09-07 20:43:16.674572
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd7ce70edd59'
down_revision: Union[str, Sequence[str], None] = 'd984f20d19c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('integration_type', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('encrypted_secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_configs_institution_id'), 'integration_configs', ['institution_id'], unique=False)
    op.create_table('config_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('proposed_by_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('previous_payload_json', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_proposals_id'), 'config_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_config_proposals_institution_id'), 'config_proposals', ['institution_id'], unique=False)
    op.create_table('academic_dossiers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('enrollment_id', sa.String(), nullable=False),
    sa.Column('dossier_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_dossiers_enrollment_id'), 'academic_dossiers', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_academic_dossiers_student_id'), 'academic_dossiers', ['student_id'], unique=False)
    op.create_table('academic_validations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dossier_id', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['academic_dossiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_validations_dossier_id'), 'academic_validations', ['dossier_id'], unique=False)
    op.create_table('dossier_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dossier_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('document_type_code', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['ecm_nodes.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['academic_dossiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossier_documents_dossier_id'), 'dossier_documents', ['dossier_id'], unique=False)
    op.add_column('ged_document_types', sa.Column('group_id', sa.String(), nullable=True))
    op.add_column('ged_document_types', sa.Column('retention_years', sa.Integer(), nullable=True))
    op.add_column('ged_document_types', sa.Column('legal_hold', sa.Boolean(), nullable=True))
    op.add_column('ged_workflow_transitions', sa.Column('allowed_roles', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ged_workflow_transitions', 'allowed_roles')
    op.drop_column('ged_document_types', 'legal_hold')
    op.drop_column('ged_document_types', 'retention_years')
    op.drop_column('ged_document_types', 'group_id')
    op.drop_index(op.f('ix_dossier_documents_dossier_id'), table_name='dossier_documents')
    op.drop_table('dossier_documents')
    op.drop_index(op.f('ix_academic_validations_dossier_id'), table_name='academic_validations')
    op.drop_table('academic_validations')
    op.drop_index(op.f('ix_academic_dossiers_student_id'), table_name='academic_dossiers')
    op.drop_index(op.f('ix_academic_dossiers_enrollment_id'), table_name='academic_dossiers')
    op.drop_table('academic_dossiers')
    op.drop_index(op.f('ix_config_proposals_institution_id'), table_name='config_proposals')
    op.drop_index(op.f('ix_config_proposals_id'), table_name='config_proposals')
    op.drop_table('config_proposals')
    op.drop_index(op.f('ix_integration_configs_institution_id'), table_name='integration_configs')
    op.drop_table('integration_configs')
    # ### end Alembic commands ###
